### ISSUE TITLE
gabisa guna mas

### ISSUE THREAD

**Issue by ju0nsus** [hanahaneull/pc-sambungkata#1]
An error occurred while executing the command: getaddrinfo ENOTFOUND api.hana.uno.
Check the console for more details.

**Comment by hanahaneull** [comment]
API nya kena delete waktu beres2 cpanel, nanti di up lagi. sambil cek masih work atau enggak.

**Comment by ju0nsus** [comment]
baikkk, terimas

**Comment by hanahaneull** [comment]
Sudah diupdate, tinggal ``git pull``
